# DESABILITADO - Projeto migrado para PostgreSQL interno no Kubernetes
# project_id = "kwbskfecgpvywxjjytai"

# Este projeto NÃO usa mais Supabase Cloud
# Toda a autenticação e dados estão no PostgreSQL interno:
# - Host: postgres.ms-frontend-picpay-monitor.svc.cluster.local
# - Database: aws_resource_db
# 
# As migrações em supabase/migrations/ são mantidas apenas como histórico
# do schema, mas NÃO são aplicadas automaticamente.
#
# Consulte ARQUITETURA_INTERNA_KUBERNETES.md para detalhes.