// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwbskfecgpvywxjjytai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3YnNrZmVjZ3B2eXd4amp5dGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDYzODYsImV4cCI6MjA3NDMyMjM4Nn0.Dc3Nw2INvGQ8nuU7nO4rPyuqE8euVFM4cazVOvMTeWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});